### ISSUE TITLE
Can't access site?

### ISSUE THREAD

**Issue by samryl** [ludumdare/dairybox#54]
I've set up according to the walkthough and ran the makefile but I can't access the site though http://ludumdare.org. The error message says 'Server not found.' and happens in IE and Firefox.
Navigating to the VM IP (192.168.48.48) yields only the directory index.
I know I'm missing something, but what is it?

**Comment by mikekasprzak** [comment]
http://ludumdare.org should have worked, but Microsoft Edge is definitely broken (Microsoft disabled something in Edge that makes it so it wont work locally). I think IE has been broken, so Firefox or Chrome are the recommended browser.

If you see the directory listing at http://192.168.48.48, then that's a good sign.

It may take a moment before ludumdare.org kicks in locally. You can try pinging it.

If you're using a 3rd party firewall, that could potentially cause problems. Try disabling it and trying again.

As a last resort, you can try adding an entry for ludumdare.org in your `hosts` file.

https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/

It should _just work_ though, since ludumdare.org is mapped to `192.168.48.48`.

**Comment by samryl** [comment]
I am not able to ping ludumdare.org. I had NetLimiter installed at one point but I've since removed it.
[EDIT] Adding it to the host file works, though.

**Comment by mikekasprzak** [comment]
Glad to hear. :smile:
